#!/usr/bin/env bash
set -eEuo pipefail

youtube-dl 'https://www.youtube.com/playlist?list=PLDiQQ7UnbGr9800e1QbOkVgQ0hwSWUEZJ'

mv -v "\"UX + Free Software = Love\" by Máirín Duffy at SeaGL 2020.mp4" "SeaGL2020-Mairin_Duffy-UX_Plus_Free_Software_Equals_Love.mp4"
mv -v "\"The Soul Of A Computer\" by Daniel Takamori at SeaGL 2020.mp4" "SeaGL2020-Daniel_Takamori-The_Soul_Of_A_Computer.mp4"
mv -v "\"Oops! I Became An Open Source Maintainer!\" by Mariatta Wijaya at SeaGL 2020.mp4" "SeaGL2020-Mariatta_Wijaya-Oops_I_Became_an_Open_Source_Maintainer.mp4"
mv -v "\"Rise Up For Free Software In Schools!\" by Mariah Villarreal at SeaGL 2020.mp4" "SeaGL2020-Mariah_Villarreal-Rise_up_for_free_software_in_schools.mp4"
mv -v "\"Patently Obvious\" by Neil McGovern at SeaGL 2020.mp4" "SeaGL2020-Neil_McGovern-Patently_Obvious.mp4"
mv -v "\"A Beginner-Inclusive Approach to Open Source\" by Ruth Ikegah at SeaGL 2020.mp4" "SeaGL2020-Ruth_Ikegah-A_Beginner_Inclusive_Approach_to_Open_Source.mp4"
mv -v "\"The Open Digital Photography Workflow\" by Stephen Wilson at SeaGL 2020.mkv" "SeaGL2020-Stephen_Wilson-The_Open_Digital_Photography_Workflow.mkv"
mv -v "\"Open Source Secrets Management\" by Gareth Greenaway at SeaGL 2020.mp4" "SeaGL2020-Gareth_J_Greenaway-Open_Source_Secrets_Management.mp4"
mv -v "\"FLOSS And You\" by DerHans at SeaGL 2020.mp4" "SeaGL2020-der_hans-FLOSS_and_you.mp4"
mv -v "\"Introducing FOSS Culture At Universities\" by Suraj Kumar Mahto at SeaGL 2020.mp4" "SeaGL2020-Suraj_Kumar_Mahto-Introducing_FOSS_Culture_at_Universities.mp4"
mv -v "\"Gaming for Good - Using Passions and Technology for Social Change\" by Josh Boykin at SeaGL 2020.mp4" "SeaGL2020-Josh_Boykin-Gaming_for_Good_Using_Passions_and_Technology_for_Social_Change.mp4"
mv -v "\"Democratizing Documentation\" by Megan Guiney at SeaGL 2020.mp4" "SeaGL2020-Megan_Guiney-Democratizing_Documentation.mp4"
mv -v "\"Features Of A Modern Terminal Emulator\" by Mike Hamrick at SeaGL 2020.mp4" "SeaGL2020-Mike_Hamrick-Features_of_a_Modern_Terminal_Emulator.mp4"
mv -v "\"Demystifying Contributor Culture\" by Jill Rouleau at SeaGL 2020.mp4" "SeaGL2020-Jill_Rouleau-Demystifying_Contributor_Culture.mp4"
mv -v "\"Let's Make Games with Rust\" by Elijah C. Voigt at SeaGL 2020.mp4" "SeaGL2020-Elijah_C_Voigt-Lets_Make_Games_with_Rust.mp4"
mv -v "\"Overclocking Your Mind And Body\" by Rowin Andruscavage at SeaGL 2020.mp4" "SeaGL2020-Rowin_Andruscavage-Overclocking_for_Your_Mind_and_Body.mp4"
mv -v "\"How To Build A Zombie Detector\" by Kaylea Champion at SeaGL 2020.mkv" "SeaGL2020-Kaylea_Champion-How_to_build_a_zombie_detector.mkv"
mv -v "\"Stand-Up Comedy About FLOSS\" by Sumana Harihareswara at SeaGL 2020.mp4" "SeaGL2020-Sumana_Harihareswara-Stand_up_comedy_about_FLOSS.mp4"
mv -v "\"Projects With A Positive Potential For Impact\" by Kathy Giori at SeaGL 2020.mp4" "SeaGL2020-Kathy_Giori-Projects_With_A_Positive_Potential_For_Impact.mp4"
mv -v "\"Building Free CI_CD With Github Actions\" by Cameron Bielstein at SeaGL 2020.mp4" "SeaGL2020-Cameron_Bielstein-Building_Free_CI_CD_with_GitHub_Actions.mp4"
mv -v "\"Open Source on the Mainframe in 1960, 1999, and Today\" by Elizabeth K. Joseph at SeaGL 2020.mp4" "SeaGL2020-Elizabeth_K_Joseph-Open_Source_on_the_Mainframe_in_1960_1999_and_Today.mp4"
mv -v "\"Crossing the Gender Divide\" by Aeva Black at SeaGL 2020.mp4" "SeaGL2020-Aeva_Black-Crossing_the_Gender_Divide.mp4"
mv -v "\"10 Vim Tricks\" by Bri Hatch at SeaGL 2020.mp4" "SeaGL2020-Bri_Hatch-10_Vim_Tricks.mp4"
mv -v "\"Introduction to Ethics from an Ethicist-in-Training\" by Molly de Blanc at SeaGL 2020.mp4" "SeaGL2020-Molly_de_Blanc-Introduction_to_Ethics_from_an_Ethicist_in_Training.mp4"
mv -v "\"Time for Action - How To Build D&I In Your Project\" by Justin W. Flory and Bee Padalkar at SeaGL 2020.mp4" "SeaGL2020-Bhagyashree_Bee_Padalkar_and_Justin_W_Flory-Time_for_Action.mp4"
mv -v "\"Alcohol & Inclusivity in Tech\" by Kara Sowles at SeaGL 2020.mp4" "SeaGL2020-Kara_Sowles-Alcohol_and_Inclusivity_in_Tech.mp4"
mv -v "\"AMA (Ask Me Anything) About Kubernetes\" by Elana Hashman at SeaGL 2020.mp4" "SeaGL2020-Elana_Hashman-AMA_About_Kubernetes.mp4"
mv -v "\"When Does A Service Take Away Your Software Freedom\" by Ian Kelling at SeaGL 2020.mp4" "SeaGL2020-Ian_Kelling-When_does_a_service_take_away_your_software_freedom.mp4"
mv -v "\"Contacts to Connections - CRM funneling for projects and people\" by WM Salt Hale at SeaGL 2020.mp4" "SeaGL2020-Wm_Salt_Hale-Contacts_to_Connections_CRM_funneling_for_projects_and_people.mp4"
mv -v "\"Move Slow and Try Not to Break Each Other\" by Deb Nicholson at SeaGL 2020.mp4" "SeaGL2020-Deb_Nicholson-Move_Slow_and_Try_Not_to_Break_Each_Other.mp4"
mv -v "\"Software Freedom Through Collective Action\" by Aaron Wolf at SeaGL 2020.mp4" "SeaGL2020-Aaron_Wolf-Software_freedom_through_collective_action.mp4"
mv -v "\"The United States' History With Free Software\" by Amanda Sopkin at SeaGL 2020.mp4" "SeaGL2020-Amanda_Sopkin-The_United_States_History_with_Free_Software.mp4"
mv -v "\"Building Alternative Networks for Fun and Resistance\" by Lisha Sterling at SeaGL 2020.mp4" "SeaGL2020-Lisha_Sterling-Building_Alternative_Networks_for_Fun_and_Resistance.mp4"
mv -v "\"Scheduling Your Open Source Project\" by Ben Cotton at SeaGL 2020.mkv" "SeaGL2020-Ben_Cotton-Scheduling_your_open_source_project.mkv"
mv -v "\"First Steps With Swift For TensorFlow\" by Tim Nugent at SeaGL 2020.mp4" "SeaGL2020-Paris_Buttfield_Addison_and_Tim_Nugent-First_steps_with_Swift_for_TensorFlow.mp4"
mv -v "\"Data Liberation - Open Source Observability\" by Nočnica Fee at SeaGL 2020.mp4" "SeaGL2020-Nocnica_Fee-Data_Liberation_Open_Source_Observability.mp4"
mv -v "\"Let's Put The Free Back In Free Market\" by VM Brasseur at SeaGL 2020.mp4" "SeaGL2020-VM_Brasseur-Lets_Put_The_Free_Back_In_Free_Market.mp4"
